# Generated by Django 5.0.4 on 2024-04-24 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_end_time_doctoravaliability_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravaliability',
            name='date',
        ),
        migrations.RemoveField(
            model_name='doctoravaliability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctoravaliability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctoravaliability',
            name='is_avaliable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AvailabilitySlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start_time', models.TimeField()),
                ('break_end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
            ],
            options={
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
