# Generated by Django 5.0.4 on 2024-04-24 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctoravaliability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslots',
            name='slot_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
